version: "2"

services:
  service:
    build:
      context: ./service
    container_name: 'http-mail-send-service'
    ports:
      - '8080:8080'
    command: "npm start"

  service-test:
    build:
      context: ./service
    container_name: 'http-mail-send-service-test'
    environment:
      - NODE_ENV=test
    command: "npm test"