version: "2"

services:
  service:
    build:
      context: ./service
    container_name: 'http-mail-send-service'
    ports:
      - '8080:8080'
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
    command: "npm start"

  service-test:
    build:
      context: ./service
    container_name: 'http-mail-send-service-test'
    environment:
      - NODE_ENV=test
    command: "npm test"

  frontend:
    build:
      context: ./frontend
    container_name: 'http-mail-send-frontend'
    environment:
     - REACT_APP_SEND_EMAIL_ENDPOINT=http://localhost:8080/send
    ports:
      - '8081:3000'
    command: "yarn start"